# Site settings
title: zach steiner
email:
description: > # this means to ignore newlines until "baseurl:"
  PhD workplace psychology. User experience design.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zachsteiner.com" # the base hostname & protocol for your site
twitter_username: zachsteiner
github_username:  zsteiner

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
    sourcemap: true

plugins: 
- jekyll-autoprefixer
- octopress-minify-html

autoprefixer:
  browsers:
  - last 4 versions
  - Safari 8
  - IE 11

exclude: 
- config.rb
- _config.yml
- README.md
- config.codekit3

exclude:
- config.codekit3
- README.md